/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-09-10 09:29:59 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@localhost/minimart -t test -s minimart
 *
 */

// Admin Users
export namespace adminusersFields {
    export type id = number;
    export type status = string;
    export type user_type = string;
    export type shop_id = number;
    export type branch_id = number;
    export type displayName = string;
    export type email = string;
    export type password = string;
}

export interface adminusers {
    id: adminusersFields.id;
    status: adminusersFields.status;
    user_type: adminusersFields.user_type;
    shop_id: adminusersFields.shop_id;
    branch_id: adminusersFields.branch_id;
    displayName: adminusersFields.displayName;
    email: adminusersFields.email;
    password: adminusersFields.password;
}

// Shops
export namespace shopsFields {
    export type shop_id = number;
    export type user_id = string;
    export type shop_name = string;
    export type shop_addr = string;
}

export interface shops {
    shop_id: shopsFields.shop_id;
    user_id: shopsFields.user_id;
    shop_name: shopsFields.shop_name;
    shop_addr: shopsFields.shop_addr;
}


// Branches
export namespace branchFields {
    export type branch_id = number;
    export type shop_id = number;
    export type branch_cat_id = number;
    export type branch_name = string;
    export type branch_addr = string;
    export type phone_no = string;
    export type currency = string;
    export type maximum_distance = string;
    export type minimum_sale = number;
    export type open_time = string;
    export type close_time = string;
    export type isAdminDelivery = number;
    export type isPosEnabled = number;
    export type track_stock = number;
    export type latitude = number;
    export type longitude = number;
    export type home_screen_theme = number;
    export type welcomeMessage = string;
    export type landmark = string;
    export type image = string;
    export type rad_three_rate = string;
    export type rad_five_rate = string;
    export type rad_ten_rate = string;
    export type rad_fifteen_rate = string;
    export type rad_twenty_rate = string;
}

export interface branches {
    branch_id: branchFields.branch_id;
    shop_id: branchFields.shop_id;
    branch_cat_id: branchFields.branch_cat_id;
    branch_name: branchFields.branch_name;
    branch_addr: branchFields.branch_addr;
    phone_no: branchFields.phone_no;
    currency: branchFields.currency;
    maximum_distance: branchFields.maximum_distance;
    minimum_sale: branchFields.minimum_sale;
    open_time: branchFields.open_time;
    close_time: branchFields.close_time;
    isAdminDelivery: branchFields.isAdminDelivery;
    isPosEnabled: branchFields.isPosEnabled;
    track_stock: branchFields.track_stock;
    latitude: branchFields.latitude;
    longitude: branchFields.longitude;
    home_screen_theme: branchFields.home_screen_theme;
    welcomeMessage: branchFields.welcomeMessage;
    landmark: branchFields.landmark;
    image: branchFields.image;
    rad_three_rate: branchFields.rad_three_rate;
    rad_five_rate: branchFields.rad_five_rate;
    rad_ten_rate: branchFields.rad_ten_rate;
    rad_fifteen_rate: branchFields.rad_fifteen_rate;
    rad_twenty_rate: branchFields.rad_twenty_rate;
}

// Branch Categories
export namespace branchCategoryFields {
    export type category_id = number;
    export type category_name = string;
    export type category_icon = string;
}

export interface branchCategory {
    category_id: branchCategoryFields.category_id;
    category_name: branchCategoryFields.category_name;
    category_icon: branchCategoryFields.category_icon;
}

// Categories
export namespace categoryFields {
    export type category_id = number;
    export type category_name = string;
    export type category_icon = string;
}

export interface category {
    category_id: categoryFields.category_id;
    category_name: categoryFields.category_name;
    category_icon: categoryFields.category_icon;
}

// Products
export namespace productFields {
    export type product_id = number;
    export type category_id = number;
    export type company = string;
    export type name = string;
    export type image = string;
    export type description = string;
    export type weight = number;
    export type sku = string;
}

export interface product {
    product_id: productFields.product_id;
    category_id: productFields.category_id;
    company: productFields.company;
    name: productFields.name;
    image: productFields.image;
    description: productFields.description;
    weight: productFields.weight;
    sku: productFields.sku;
}

// Shop Items
export namespace shopItemsFields {
    export type item_id = string;
    export type branch_ids = Array<number>;
    export type product_id = number;
    export type item_price = number;
    export type item_discount = number;
    export type remarks = string;
    export type item_qr_code = string;
    export type articleNumber = string;
    export type item_quantity = number;
    export type max_items_per_order = number;
    export type availability = number;
    export type hidden = number;
}

export interface shopItems {
    item_id: shopItemsFields.item_id;
    branch_ids: shopItemsFields.branch_ids;
    product_id: shopItemsFields.product_id;
    item_price: shopItemsFields.item_price;
    item_discount: shopItemsFields.item_discount;
    remarks: shopItemsFields.remarks;
    item_qr_code: shopItemsFields.item_qr_code;
    articleNumber: shopItemsFields.articleNumber;
    item_quantity: shopItemsFields.item_quantity;
    max_items_per_order: shopItemsFields.max_items_per_order;
    availability: shopItemsFields.availability;
    hidden: shopItemsFields.hidden;
}

// Address
export namespace addressFields {
    export type address_id = number;
    export type uid = string;
    export type unit_number = string;
    export type condo_name = string;
    export type address = string;
    export type pin_code = string;
    export type latitude = string;
    export type logitude = string;
    export type active = number;
}

export interface address {
    address_id: addressFields.address_id;
    uid: addressFields.uid;
    unit_number: addressFields.unit_number;
    condo_name: addressFields.condo_name;
    address: addressFields.address;
    pin_code: addressFields.pin_code;
    latitude: addressFields.latitude;
    logitude: addressFields.logitude;
    active: addressFields.active;
}

// Sale Item
export namespace saleItemFields {
    export type sales_details_id = string;
    export type sales_id = string;
    export type product_id = number;
    export type item_id = string;
    export type quantity = number;
    export type item_price = number;
    export type discount = number;
}

export interface saleItem {
    sales_details_id: saleItemFields.sales_details_id;
    sales_id: saleItemFields.sales_id;
    product_id: saleItemFields.product_id;
    item_id: saleItemFields.item_id;
    quantity: saleItemFields.quantity;
    item_price: saleItemFields.item_price;
    discount: saleItemFields.discount;
}

// Sale Status
export namespace saleStatusFields {
    export type status_id = number;
    export type sales_id = string;
    export type status = string;
    export type updated_by = string;
    export type date = string;
}

export interface saleStatus {
    status_id: saleStatusFields.status_id;
    sales_id: saleStatusFields.sales_id;
    status: saleStatusFields.status;
    updated_by: saleStatusFields.updated_by;
    date: saleStatusFields.date;
}

// Users
export namespace userFields {
    export type uid = string;
    export type displayName = string;
    export type email = string;
    export type phoneNumber = String;
    export type photoUrl = string;
    export type totalPoints = string;
    export type providerId = string;
    export type fcmToken = string;
    export type deviceName = string;
    export type deviceOs = string;
    export type loginStatus = boolean;
}

export interface user {
    uid: userFields.uid;
    displayName: userFields.displayName;
    email: userFields.email;
    phoneNumber: userFields.phoneNumber;
    photoUrl: userFields.photoUrl;
    totalPoints: userFields.totalPoints;
    providerId: userFields.providerId;
    fcmToken: userFields.fcmToken;
    deviceName: userFields.deviceName;
    deviceOs: userFields.deviceOs;
    loginStatus: userFields.loginStatus;
}

// Shop Service List
export namespace deliveryVendorsListFields {
    export type delivery_vendor_id = number;
    export type del_ven_name = number;
    export type del_ven_endpoint = string;
    export type key = string;
    export type secret = string;
    export type country = number;
}

export interface deliveryVendorsList {
    delivery_vendor_id: deliveryVendorsListFields.delivery_vendor_id;
    del_ven_name: deliveryVendorsListFields.del_ven_name;
    del_ven_endpoint: deliveryVendorsListFields.del_ven_endpoint;
    key: deliveryVendorsListFields.key;
    secret: deliveryVendorsListFields.secret;
    country: deliveryVendorsListFields.country;
}
// Shops with branches
export namespace ShopAndBranchesFields {
    export type shop_id = number;
    export type branch_id = number;
    export type shop_name = string;
    export type image = string;
    export type branch_name = string;
    export type currency = string;
    export type isPosEnabled = number;
    export type active = number;
}

export interface ShopAndBranches {
    shop_id: ShopAndBranchesFields.shop_id;
    branch_id: ShopAndBranchesFields.branch_id;
    shop_name: ShopAndBranchesFields.shop_name;
    image: ShopAndBranchesFields.image;
    branch_name: ShopAndBranchesFields.branch_name;
    currency: ShopAndBranchesFields.currency;
    isPosEnabled: ShopAndBranchesFields.isPosEnabled;
    active: ShopAndBranchesFields.active;
}

// Delivery Shops
export namespace DeliveryShopsFields {
    export type delivery_shop_id = number;
    export type vendor_id = number;
    export type branch_id = number;
}

export interface DeliveryShops {
    delivery_shop_id: DeliveryShopsFields.delivery_shop_id;
    vendor_id: DeliveryShopsFields.vendor_id;
    branch_id: DeliveryShopsFields.branch_id;
}

// Delivery Vendory for branch List
export namespace DeliveryVendorsOfBranchFields {
    export type delivery_vendor_id = number;
    export type del_ven_name = string;
    export type del_ven_endpoint = string;
    export type key = string;
    export type secret = string;
    export type country = string;
    export type delivery_shop_id = number;
    export type vendor_id = number;
    export type branch_id = number;
    export type status = number;
}

export interface DeliveryVendorsOfBranch {
    delivery_vendor_id: DeliveryVendorsOfBranchFields.delivery_vendor_id;
    del_ven_name: DeliveryVendorsOfBranchFields.del_ven_name;
    del_ven_endpoint: DeliveryVendorsOfBranchFields.del_ven_endpoint;
    key: DeliveryVendorsOfBranchFields.key;
    secret: DeliveryVendorsOfBranchFields.secret;
    country: DeliveryVendorsOfBranchFields.country;
    delivery_shop_id: DeliveryVendorsOfBranchFields.delivery_shop_id;
    vendor_id: DeliveryVendorsOfBranchFields.vendor_id;
    branch_id: DeliveryVendorsOfBranchFields.branch_id;
    status: DeliveryVendorsOfBranchFields.status;
}

// Promotions
export namespace PromotionsFields {
    export type promo_id = number;
    export type branch_id = number;
    export type picture = string;
    export type title = string;
    export type description = string;
    export type start_date = string;
    export type end_date = string;
    export type discount = number;
    export type created_date = string;
    export type status = number;
    // export type products = { id: number, percentage: string }[];
}

export interface Promotions {
    promo_id: PromotionsFields.promo_id;
    branch_id: PromotionsFields.branch_id;
    picture: PromotionsFields.picture;
    title: PromotionsFields.title;
    description: PromotionsFields.description;
    start_date: PromotionsFields.start_date;
    end_date: PromotionsFields.end_date;
    discount: PromotionsFields.discount;
    created_date: PromotionsFields.created_date;
    status: PromotionsFields.status;
    // products: PromotionsFields.products;
}

// Promotions Products
export namespace PromotionsProductFields {
    export type promo_items_id = string;
    export type promo_id = string;
    export type shop_items_id = string;
    export type percentage = string;
}

export interface PromotionItem {
    promo_items_id: PromotionsProductFields.promo_items_id;
    promo_id: PromotionsProductFields.promo_id;
    shop_items_id: PromotionsProductFields.shop_items_id;
    percentage: PromotionsProductFields.percentage;
}


// Payment Gateway
export namespace paymentgatewayListFields {
    export type payment_gateway_id = number;
    export type payment_gateway_name = string;
    export type payment_currency = string;
    export type publish_token = string;
    export type secret_key = string;
}
export interface paymentgatewayList {
    payment_gateway_id: paymentgatewayListFields.payment_gateway_id;
    payment_gateway_name: paymentgatewayListFields.payment_gateway_name;
    payment_currency: paymentgatewayListFields.payment_currency;
    publish_token: paymentgatewayListFields.publish_token;
    secret_key: paymentgatewayListFields.secret_key;
}


// Payment Gateway Branches
export namespace PaymentGatewayBranchFields {
    export type payment_gateway_branchid = number;
    export type payment_gateway_id = number;
    export type branch_id = number;
}

export interface PaymentGatewayBranch {
    payment_gateway_branchid: PaymentGatewayBranchFields.payment_gateway_branchid;
    payment_gateway_id: PaymentGatewayBranchFields.payment_gateway_id;
    branch_id: PaymentGatewayBranchFields.branch_id;
}

// Payment Gateway for branch List
export namespace PaymentGatewayOfBranchFields {
    export type payment_gateway_id = number;
    export type payment_gateway_name = string;
    export type payment_currency = string;
    export type publish_token = string;
    export type secret_key = string;
    export type payment_gateway_branchid = number;
    export type branch_id = number;
    export type status = number;
}

export interface PaymentGatewayOfBranch {
    payment_gateway_id: PaymentGatewayOfBranchFields.payment_gateway_id;
    payment_gateway_name: PaymentGatewayOfBranchFields.payment_gateway_name;
    payment_currency: PaymentGatewayOfBranchFields.payment_currency;
    publish_token: PaymentGatewayOfBranchFields.publish_token;
    secret_key: PaymentGatewayOfBranchFields.secret_key;
    payment_gateway_branchid: PaymentGatewayOfBranchFields.payment_gateway_branchid;
    branch_id: PaymentGatewayOfBranchFields.branch_id;
    status: PaymentGatewayOfBranchFields.status;
}